name: Shell commands

on: push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    
    steps:
      - name: echo a string
        run: echo "Hello World!"
      - name: multiline script
        run: |
          node -v
          java -version
          npm -v
          echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/logs"
          echo "echo ${{ github.job }}"
      - name: Output Current Job Log URL
        uses: actions/github-script@v6
        id: job-url
        with:
          script: |
              const { data } = await github.rest.actions.listJobsForWorkflowRunAttempt({
                ...context.repo,
                run_id: context.runId,
                attempt_number: process.env.GITHUB_RUN_ATTEMPT,
              });

              return data.jobs[0].html_url
          result-encoding: string
      - name: Print Log URL
        run: |
          echo "Log URL: ${{ steps.job-url.outputs.result }}"
