name: Shell commands

on: push

# jobs:
#   run-shell-commands:
#     runs-on: ubuntu-latest
#     steps:
#       - name: echo a string
#         run: echo "Hello World!"
#       - name: multiline script
#         run: |
#           node -v
#           java -version
#           npm -v
#           echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs"
#           echo "echo ${{ github.job }}"
#       - name: Output Current Job Log URL
#         run: echo ${{ github.job.outputs.html_url }}

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}

